# special thanks to github user Muqtxdir who helped me to created this!
name: yaru-colors
version: "21.04"
base: core18
architectures:
  - all
summary: Yaru-Colors GTK themes and icons
description: |
  A snap that exports the Yaru-Colors GTK and icon themes.

grade: stable
confinement: strict

slots:
  gtk-2-themes:
    interface: content
    source:
      read:
        - $SNAP/share/gtk2/Yaru-Amber
        - $SNAP/share/gtk2/Yaru-Amber-light
        - $SNAP/share/gtk2/Yaru-Amber-dark
        - $SNAP/share/gtk2/Yaru-Aqua
        - $SNAP/share/gtk2/Yaru-Aqua-light
        - $SNAP/share/gtk2/Yaru-Aqua-dark
        - $SNAP/share/gtk2/Yaru-Aubergine
        - $SNAP/share/gtk2/Yaru-Aubergine-light
        - $SNAP/share/gtk2/Yaru-Aubergine-dark
        - $SNAP/share/gtk2/Yaru-Blue
        - $SNAP/share/gtk2/Yaru-Blue-light
        - $SNAP/share/gtk2/Yaru-Blue-dark
        - $SNAP/share/gtk2/Yaru-Brown
        - $SNAP/share/gtk2/Yaru-Brown-light
        - $SNAP/share/gtk2/Yaru-Brown-dark
        - $SNAP/share/gtk2/Yaru-Cinnamon
        - $SNAP/share/gtk2/Yaru-Cinnamon-light
        - $SNAP/share/gtk2/Yaru-Cinnamon-dark
        - $SNAP/share/gtk2/Yaru-Deepblue
        - $SNAP/share/gtk2/Yaru-Deepblue-light
        - $SNAP/share/gtk2/Yaru-Deepblue-dark
        - $SNAP/share/gtk2/Yaru-Green
        - $SNAP/share/gtk2/Yaru-Green-light
        - $SNAP/share/gtk2/Yaru-Green-dark
        - $SNAP/share/gtk2/Yaru-Grey
        - $SNAP/share/gtk2/Yaru-Grey-light
        - $SNAP/share/gtk2/Yaru-Grey-dark
        - $SNAP/share/gtk2/Yaru-Lavender
        - $SNAP/share/gtk2/Yaru-Lavender-light
        - $SNAP/share/gtk2/Yaru-Lavender-dark
        - $SNAP/share/gtk2/Yaru-MATE
        - $SNAP/share/gtk2/Yaru-MATE-light
        - $SNAP/share/gtk2/Yaru-MATE-dark
        - $SNAP/share/gtk2/Yaru-Orange
        - $SNAP/share/gtk2/Yaru-Orange-light
        - $SNAP/share/gtk2/Yaru-Orange-dark
        - $SNAP/share/gtk2/Yaru-Pink
        - $SNAP/share/gtk2/Yaru-Pink-light
        - $SNAP/share/gtk2/Yaru-Pink-dark
        - $SNAP/share/gtk2/Yaru-Purple
        - $SNAP/share/gtk2/Yaru-Purple-light
        - $SNAP/share/gtk2/Yaru-Purple-dark
        - $SNAP/share/gtk2/Yaru-Red
        - $SNAP/share/gtk2/Yaru-Red-light
        - $SNAP/share/gtk2/Yaru-Red-dark
        - $SNAP/share/gtk2/Yaru-Teal
        - $SNAP/share/gtk2/Yaru-Teal-light
        - $SNAP/share/gtk2/Yaru-Teal-dark
        - $SNAP/share/gtk2/Yaru-Yellow
        - $SNAP/share/gtk2/Yaru-Yellow-light
        - $SNAP/share/gtk2/Yaru-Yellow-dark


  gtk-3-themes:
    interface: content
    source:
      read:
        - $SNAP/share/themes/Yaru-Amber
        - $SNAP/share/themes/Yaru-Amber-light
        - $SNAP/share/themes/Yaru-Amber-dark
        - $SNAP/share/themes/Yaru-Aqua
        - $SNAP/share/themes/Yaru-Aqua-light
        - $SNAP/share/themes/Yaru-Aqua-dark
        - $SNAP/share/themes/Yaru-Aubergine
        - $SNAP/share/themes/Yaru-Aubergine-light
        - $SNAP/share/themes/Yaru-Aubergine-dark
        - $SNAP/share/themes/Yaru-Blue
        - $SNAP/share/themes/Yaru-Blue-light
        - $SNAP/share/themes/Yaru-Blue-dark
        - $SNAP/share/themes/Yaru-Brown
        - $SNAP/share/themes/Yaru-Brown-light
        - $SNAP/share/themes/Yaru-Brown-dark
        - $SNAP/share/themes/Yaru-Cinnamon
        - $SNAP/share/themes/Yaru-Cinnamon-light
        - $SNAP/share/themes/Yaru-Cinnamon-dark
        - $SNAP/share/themes/Yaru-Deepblue
        - $SNAP/share/themes/Yaru-Deepblue-light
        - $SNAP/share/themes/Yaru-Deepblue-dark
        - $SNAP/share/themes/Yaru-Green
        - $SNAP/share/themes/Yaru-Green-light
        - $SNAP/share/themes/Yaru-Green-dark
        - $SNAP/share/themes/Yaru-Grey
        - $SNAP/share/themes/Yaru-Grey-light
        - $SNAP/share/themes/Yaru-Grey-dark
        - $SNAP/share/themes/Yaru-Lavender
        - $SNAP/share/themes/Yaru-Lavender-light
        - $SNAP/share/themes/Yaru-Lavender-dark
        - $SNAP/share/themes/Yaru-MATE
        - $SNAP/share/themes/Yaru-MATE-light
        - $SNAP/share/themes/Yaru-MATE-dark
        - $SNAP/share/themes/Yaru-Orange
        - $SNAP/share/themes/Yaru-Orange-light
        - $SNAP/share/themes/Yaru-Orange-dark
        - $SNAP/share/themes/Yaru-Pink
        - $SNAP/share/themes/Yaru-Pink-light
        - $SNAP/share/themes/Yaru-Pink-dark
        - $SNAP/share/themes/Yaru-Purple
        - $SNAP/share/themes/Yaru-Purple-light
        - $SNAP/share/themes/Yaru-Purple-dark
        - $SNAP/share/themes/Yaru-Red
        - $SNAP/share/themes/Yaru-Red-light
        - $SNAP/share/themes/Yaru-Red-dark
        - $SNAP/share/themes/Yaru-Teal
        - $SNAP/share/themes/Yaru-Teal-light
        - $SNAP/share/themes/Yaru-Teal-dark
        - $SNAP/share/themes/Yaru-Yellow
        - $SNAP/share/themes/Yaru-Yellow-light
        - $SNAP/share/themes/Yaru-Yellow-dark

  icon-themes:
    interface: content
    source:
      read:
        - $SNAP/share/icons/Yaru-Amber
        - $SNAP/share/icons/Yaru-Aqua
        - $SNAP/share/icons/Yaru-Aubergine
        - $SNAP/share/icons/Yaru-Blue
        - $SNAP/share/icons/Yaru-Brown
        - $SNAP/share/icons/Yaru-Cinnamon
        - $SNAP/share/icons/Yaru-Deepblue
        - $SNAP/share/icons/Yaru-Green
        - $SNAP/share/icons/Yaru-Grey
        - $SNAP/share/icons/Yaru-Lavender
        - $SNAP/share/icons/Yaru-MATE
        - $SNAP/share/icons/Yaru-Orange
        - $SNAP/share/icons/Yaru-Pink
        - $SNAP/share/icons/Yaru-Purple
        - $SNAP/share/icons/Yaru-Red
        - $SNAP/share/icons/Yaru-Teal
        - $SNAP/share/icons/Yaru-Yellow


parts:
  theme:
    after: [utils]
    plugin: nil
    source: https://github.com/Jannomag/Yaru-colors.git
    source-type: git
    source-tag: 21.04snap
    build-packages:
      - sassc
      - libcanberra-gtk-module
      - libglib2.0-dev
    override-build: |
        snapcraftctl build
        mkdir -p $SNAPCRAFT_PART_INSTALL/share/themes
        ./install.sh --snapthemes $SNAPCRAFT_PART_INSTALL/share/themes
        $SNAPCRAFT_STAGE/split-gtk-theme.sh $SNAPCRAFT_PART_INSTALL
        mkdir -p $SNAPCRAFT_PART_INSTALL/share/icons
        ./install.sh --snapicons $SNAPCRAFT_PART_INSTALL/share/icons
        $SNAPCRAFT_STAGE/update-icon-cache.sh $SNAPCRAFT_PART_INSTALL/share/icons
    stage:
      - share/gtk2/*/gtk-2.0
      - share/themes/*/gtk-3*
      - share/icons/Yaru-*

  utils:
    plugin: dump
    source: utils
    prime:
      - -*
    build-packages:
      - try: [gtk-update-icon-cache]
      - else: [libgtk-3-bin]
