name: communitheme
version: '0.1'
architectures: [all]
summary: The next Ubuntu theme built by the community.
description: |
  Yaru, formerly known as Communitheme, is the new Ubuntu theme built by the community. Yaru will become the default Ubuntu theme in Ubuntu 18.10. This package allows you to try out the theme on Ubuntu 18.04 LTS.

  To try out the theme, install this package on Ubuntu 18.04 LTS, restart your computer and select the "Ubuntu with communitheme snap" session from the login screen.

  More information is available at
  https://community.ubuntu.com/t/faq-ubuntu-new-theme/1930.
icon: snap/assets/Yaru256.png
grade: stable
confinement: strict

parts:
  theme:
    source: .
    plugin: meson
    build-packages: ["sassc", "libglib2.0-dev"]
    meson-parameters: ["--prefix=/"]
    override-build: |
      # Rename the theme name to previous name for backward compatibility
      sed -i 's/Yaru/Communitheme/' meson.build
      # First run normal build stage (the build stage of the meson plugin)
      snapcraftctl build
      # Link session file
      ln -s snap/session $SNAPCRAFT_PART_INSTALL/session
      # backward compability naming with symlinks and names
      mv $SNAPCRAFT_PART_INSTALL/share/icons/Communitheme $SNAPCRAFT_PART_INSTALL/share/icons/communitheme
      sed -i 's/Communitheme/communitheme/' $SNAPCRAFT_PART_INSTALL/share/icons/communitheme/cursor.theme
      ln -s communitheme $SNAPCRAFT_PART_INSTALL/share/icons/Suru
      sed -i 's/Communitheme/Suru/' $SNAPCRAFT_PART_INSTALL/share/icons/Suru/index.theme
      mv $SNAPCRAFT_PART_INSTALL/share/sounds/Communitheme $SNAPCRAFT_PART_INSTALL/share/sounds/communitheme
      sed -i 's/Communitheme/communitheme/' $SNAPCRAFT_PART_INSTALL/share/sounds/communitheme/*.theme
      mv $SNAPCRAFT_PART_INSTALL/share/gnome-shell/modes/communitheme.json $SNAPCRAFT_PART_INSTALL/share/gnome-shell/modes/ubuntu-communitheme.json
      # remove unused artefacts in the snap (sessions and schemas)
      rm -rf $SNAPCRAFT_PART_INSTALL/share/*sessions $SNAPCRAFT_PART_INSTALL/share/glib-2.0
      # don't support dark variant until it's ready
      #rm -r $SNAPCRAFT_PART_INSTALL/share/themes/*-dark
